// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8akzUNtKnTlta6PEzlpKyEJQ-bow8XkA',
    appId: '1:270380758196:web:bc269971a0ee30921493e1',
    messagingSenderId: '270380758196',
    projectId: 'fleet-tractor-394510',
    authDomain: 'fleet-tractor-394510.firebaseapp.com',
    databaseURL: 'https://fleet-tractor-394510-default-rtdb.firebaseio.com',
    storageBucket: 'fleet-tractor-394510.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlnoGZLphCK0ec9z_-0re2eAeIyRLVDw8',
    appId: '1:270380758196:android:f4124b7b5a08ded31493e1',
    messagingSenderId: '270380758196',
    projectId: 'fleet-tractor-394510',
    databaseURL: 'https://fleet-tractor-394510-default-rtdb.firebaseio.com',
    storageBucket: 'fleet-tractor-394510.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI7JrM98ikKJ6nCjIkC0Mm5eGkjXxMda0',
    appId: '1:270380758196:ios:8bd8fb288339d4291493e1',
    messagingSenderId: '270380758196',
    projectId: 'fleet-tractor-394510',
    databaseURL: 'https://fleet-tractor-394510-default-rtdb.firebaseio.com',
    storageBucket: 'fleet-tractor-394510.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI7JrM98ikKJ6nCjIkC0Mm5eGkjXxMda0',
    appId: '1:270380758196:ios:9675a1e15873719f1493e1',
    messagingSenderId: '270380758196',
    projectId: 'fleet-tractor-394510',
    databaseURL: 'https://fleet-tractor-394510-default-rtdb.firebaseio.com',
    storageBucket: 'fleet-tractor-394510.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
